version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 45s
      interval: 5s
      retries: 20
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  app:
    build:
      context: ./app
    depends_on:
      mysql:
        condition: service_healthy
    tty: true
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ./main
