apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        # ローカルでビルドしたイメージを使用
        - image: goapi:1.0
          name: goapi-sample
          envFrom:
            - configMapRef:
                name: api
            - secretRef:
                name: api
          resources: {}
status: {}
