apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 8080 # GoAPIを起動しているポート
  selector:
    app: api
  type: ClusterIP
status:
  loadBalancer: {}
