apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: https://github.com/itoi10/k8s_cicd
    targetRevision: main
    path: k8s_manifest/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}