# 参考 ワークフローでのGitHub Packagesの管理
# https://docs.github.com/ja/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

# DockerイメージをビルドしGitHub Packagesにプッシュするワークフロー
name: Create and publish a Docker image

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # metaステップのtagsをアプトプットに設定
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  update-manifest:
    # 前のジョブが終わっていることが前提
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      # ※今回は同じリポジトリのupd-mftブランチのマニフェストを変更する
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upd-mft

      - name: Update manifest file
        env:
          YAML_PATH: k8s_manifest/api/api-deployment.yaml
          CONTAINER_NAME: goapi-sample
          IMAGE_FULL_NAME: ${{ needs.build-and-push-image.outputs.tags }} # 前のジョブのoutput参照
        # yqコマンドでyamlファイル書き換え. goapi-sampleコンテナのイメージを更新
        run: |
          yq e -i "(.spec.template.spec.containers[]|select(.name == \"${CONTAINER_NAME}\").image)|=\"${IMAGE_FULL_NAME}\"" ${YAML_PATH}
          cat ${YAML_PATH}
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update goapi-sample"
          base: upd-mft
          draft: true
          body: |
            # Changes
            - Update `goapi-sample` image
